<?php
require __DIR__ . '/../src/Config/Database.php';
require __DIR__ . '/../src/Models/User.php';

use App\Config\Database;

echo "<h1>Update Password</h1>";

try {
    $db = Database::getInstance()->getConnection();
    // Hash for 'admin123' generated by the previous test script
    $newHash = password_hash('admin123', PASSWORD_DEFAULT);

    $stmt = $db->prepare("UPDATE users SET password_hash = ? WHERE username = 'admin'");
    $result = $stmt->execute([$newHash]);

    if ($result) {
        echo "Password updated successfully for user 'admin'.<br>";
        echo "New Hash: " . $newHash;
    } else {
        echo "Failed to update password.";
    }
} catch (Exception $e) {
    echo "Error: " . $e->getMessage();
}
